language: node_js
node_js:
  - "lts/*"
addons:
  apt:
    packages:
      - xvfb
install:
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm install -g typescript
  - tsc
script:
  - node dist/index.js
after_success:
  - sh .travis-push.sh