language: node_js
node_js:
  - "lts/*"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_script:
  - npm install -g typescript
  - tsc
script:
  - node dist/index.js
after_success:
  - sh .travis-push.sh